drop table if exists shows;

-- Create the table anew
create table shows (
  id INTEGER primary key generated by default as identity,
  showname text,
  startdate Date,
  finishdate Date,
  genre text,
  seasons INTEGER,
  showdescription text,
  showlanguage text,
  currentseason INTEGER,
  towatch boolean,
  watching boolean,
  finish boolean
);
