drop table if exists shows;

-- Create the table anew
create table shows (
  id INTEGER primary key generated by default as identity,
  showName text,
  startDate Date,
  finishDate Date,
  genre text,
  seasons INTEGER,
  showDescription text,
  showLanguage text,
  currentSeason INTEGER
);

